# .github/workflows/ci-cd-pipeline.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build Stage
        run: echo "Building the project..."
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Test Stage
        run: echo "Running tests..."
      
  docker_build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Docker Build Stage
        run: echo "Building Docker images..."
      
  deploy:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy Stage
        run: echo "Deploying the application..."
