name: Build and Push Docker Image

on:
  push:
    branches: [ master ]  # or any branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set_tag.outputs.IMAGE_TAG }}

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set image tag
      id: set_tag
      run: echo "::set-output name=IMAGE_TAG::$(echo 3242executer/snake-js:latest)"

    - name: Build the Docker image
      run: docker build -t ${{ steps.set_tag.outputs.IMAGE_TAG }} .

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push the Docker image to Docker Hub
      run: docker push ${{ needs.build.outputs.IMAGE_TAG }}
